/**
 * The plan check-in convention, written into the repository's agent instructions.
 *
 * opencodewiki derives a plan's date, feature scope, and whether it actually shipped from the
 * commit that adds it — not from its filename, which Claude Code generates from the opening words
 * of a prompt and which carries no signal. That makes *how* a plan is committed the thing that
 * determines how much the plan is worth as evidence.
 *
 * Rather than cope with whatever arrives, the plugin states the convention where the agent doing
 * the implementing will read it. Writing between markers keeps the block idempotent and leaves
 * everything the operator wrote around it untouched.
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const START = "<!-- OPENCODEWIKI:START -->";
const END = "<!-- OPENCODEWIKI:END -->";

export const PLAN_CONVENTION = `## Plan check-in convention

This repository's wiki is generated by opencodewiki, which reads the plans directory as evidence of
*why* the code looks the way it does — intent, decisions taken, and alternatives rejected. Source
code shows what the system does; only plans record what was considered and turned down.

Plan filenames are auto-generated and carry no meaning, so opencodewiki reads each plan's date,
feature, and whether it shipped from **the commit that adds it**. How you commit a plan therefore
decides how much it counts.

When you implement from a plan:

- **Commit the plan together with the implementation, never ahead of it.** A plan committed early
  records intent that may never have happened, and the wiki cannot tell that apart from a decision.
- **Put it in the final commit of the feature.** Implementations usually span several commits; the
  last one is the point at which the plan is actually true.
- **If the implementation diverged, update the plan before committing it.** Check in the plan that
  describes what you built, not what you set out to build — a stale plan becomes a confident false
  claim in the wiki, which is worse than no plan at all.
- **Write that commit's message about the whole feature**, not only the files in that diff. That
  subject line is read as the statement of what the plan delivered.
- **Use a conventional-commit type and scope** — \`feat(auth):\`, \`fix(search):\`, \`perf(api):\`.
  The scope is how plans are grouped into features, and the type distinguishes new behaviour from
  repair.`;

export interface AgentDocResult {
  file: string;
  action: "created" | "updated" | "unchanged";
}

/**
 * Inserts or refreshes the convention block in one agent instructions file.
 *
 * Only the region between the markers is ever rewritten, so hand-written guidance either side
 * survives untouched — the operator owns the file, the plugin owns one block in it.
 */
export async function writeAgentDoc(file: string, body: string): Promise<AgentDocResult> {
  const block = `${START}\n${body}\n${END}`;
  const existing = await readFile(file, "utf8").catch(() => null);

  if (existing === null) {
    await writeFile(file, `${block}\n`, "utf8");
    return { file, action: "created" };
  }

  const from = existing.indexOf(START);
  const to = existing.indexOf(END);

  if (from !== -1 && to !== -1 && to > from) {
    const next = existing.slice(0, from) + block + existing.slice(to + END.length);
    if (next === existing) return { file, action: "unchanged" };
    await writeFile(file, next, "utf8");
    return { file, action: "updated" };
  }

  const separator = existing.endsWith("\n") ? "\n" : "\n\n";
  await writeFile(file, `${existing}${separator}${block}\n`, "utf8");
  return { file, action: "updated" };
}

/**
 * Writes the convention into every agent instructions file the repository already uses.
 *
 * Existing files are always updated. When none exist, `CLAUDE.md` is created — but only that one,
 * since minting an `AGENTS.md` in a repo that never had one is a decision for the operator.
 */
export async function writePlanConvention(repoRoot: string): Promise<AgentDocResult[]> {
  const candidates = ["CLAUDE.md", "AGENTS.md"].map((name) => path.join(repoRoot, name));
  const present: string[] = [];
  for (const candidate of candidates) {
    if ((await readFile(candidate, "utf8").catch(() => null)) !== null) present.push(candidate);
  }
  const targets = present.length > 0 ? present : [candidates[0] as string];
  return Promise.all(targets.map((file) => writeAgentDoc(file, PLAN_CONVENTION)));
}
